services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017   # Expose MongoDB port 27017 to the host
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - "./apps/deploy/db:/data/db"
      # Windows path mapped to MongoDB data directory

  mongo-express:
    image: mongo-express
    restart: always
    ports:
#     - external : internal
      - 8045:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: adminadminadmin
      ME_CONFIG_BASICAUTH_PASSWORD: adminadminadmin
