info:
  name: Add Task
  type: http
  seq: 2

http:
  method: POST
  url: http://localhost:8080/tasks/addTask
  body:
    type: json
    data: |-
      {
        "taskName": "Implement back door",
        "difficulty": "hard",
        "taskDesc": "Kill application",
        "effort": 0
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
