info:
  name: Delete Task
  type: http
  seq: 4

http:
  method: DELETE
  url: http://localhost:8080/tasks/delete/{{id}}
  auth: inherit

runtime:
  variables:
    - name: id
      value: T-001

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
