info:
  name: Get All Tasks
  type: http
  seq: 3

http:
  method: GET
  url: http://localhost:8080/tasks/
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
