info:
  name: Get by Task Name
  type: http
  seq: 5

http:
  method: GET
  url: http://localhost:8080/tasks/findByName?name=Design
  params:
    - name: name
      value: Design
      type: query
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
