opencollection: 1.0.0

info:
  name: Tasks
config:
  proxy:
    inherit: true
    config:
      protocol: http
      hostname: ""
      port: ""
      auth:
        username: ""
        password: ""
      bypassProxy: ""
bundled: false
extensions:
  bruno:
    ignore:
      - node_modules
      - .git
    presets:
      request:
        type: http
        url: http://localhost:8080/tasks/
